/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'MAYAN' at '1/21/16 7:45 PM' with Gradle 1.9
 *
 * @author MAYAN, @date 1/21/16 7:45 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
